export enum messageTypes  {
  TEXTMESSAGE= 101,
  PICTUREMESSAGE= 102,
  VOICEMESSAGE= 103,
  VIDEOMESSAGE= 104,
  FILEMESSAGE= 105,
  ATTEXTMESSAGE= 106,
  MERGERMESSAGE= 107,
  CARDMESSAGE= 108,
  LOCATIONMESSAGE= 109,
  CUSTOMMESSAGE= 110,
  REVOKEMESSAGE= 111,
  HASREADRECEIPTMESSAGE= 112,
  TYPINGMESSAGE= 113,
  QUOTEMESSAGE= 114,
};


export enum tipsTypes  {
  REVOKEMESSAGE = 111,
  ACCEPTFRIENDNOTICE= 201,
  ADDFRIENDNOTICE= 202,
  REFUSEFRIENDAPPLICATIONNOTICE= 203,
  SETSELFINFONOTICE= 204,
  REVOKEMESSAGENOTICE= 205,
  C2CMESSAGEASREADNOTICE= 206,
  KICKONLIENNOTICE= 303,
  TRANSFERGROUPOWNERNOTICE= 501,
  CREATEGROUPNOTICE= 502,
  JOINGROUPNOTICE= 504,
  QUITGROUPNOTICE= 505,
  SETGROUPINFONOTICE= 506,
  ACCEPTGROUPAPPLICATIONNOTICE= 507,
  REFUSEGROUPAPPLICATIONNOTICE= 508,
  KICKGROUPMEMBERNOTICE= 509,
  INVITETOGROUPNOTICE= 510,
};


export const nomalMessageTypes = [
  messageTypes.TEXTMESSAGE,
  messageTypes.ATTEXTMESSAGE,
  messageTypes.CARDMESSAGE,
  messageTypes.MERGERMESSAGE,
  messageTypes.LOCATIONMESSAGE,
  messageTypes.CUSTOMMESSAGE,
  messageTypes.REVOKEMESSAGE,
  messageTypes.HASREADRECEIPTMESSAGE,
  messageTypes.TYPINGMESSAGE,
  messageTypes.QUOTEMESSAGE
]

export const notOssMessageTypes = [
  messageTypes.PICTUREMESSAGE,
  messageTypes.VIDEOMESSAGE,
  messageTypes.VOICEMESSAGE,
  messageTypes.FILEMESSAGE
]

export enum SessionType {
  SINGLECVE = 1,
  GROUPCVE = 2
}